# Namespace and overrides
namespace: midpoint
nameOverride: midpoint
fullnameOverride: midpoint
imagePullSecrets: []

# Secret for Postgres
secret:
  name: midpoint-db-secret
  stringData:
    POSTGRES_PASSWORD: db.secret.pw.007

# Postgres configuration
postgres:
  enabled: true
  name: midpoint-postgres
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  env:
    - name: POSTGRES_USER
      value: midpoint
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: midpoint-db-secret
          key: POSTGRES_PASSWORD
    - name: POSTGRES_INITDB_ARGS
      value: --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
    hostPath: /mnt/data/postgres
    accessModes:
      - ReadWriteOnce

# MidPoint application configuration
app:
  enabled: true
  name: midpoint
  replicaCount: 1
  image:
    repository: evolveum/midpoint
    tag: 4.8.4-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  env:
    - name: MP_SET_midpoint_repository_type
      value: native
    - name: MP_SET_midpoint_repository_database
      value: postgresql
    - name: MP_SET_midpoint_repository_jdbcUsername
      value: midpoint
    - name: MP_SET_midpoint_repository_jdbcPassword
      valueFrom:
        secretKeyRef:
          name: midpoint-db-secret
          key: POSTGRES_PASSWORD
    - name: MP_SET_midpoint_repository_jdbcUrl
      value: jdbc:postgresql://midpoint-postgres:5432/midpoint
    - name: MP_UNSET_midpoint_repository_hibernateHbm2ddl
      value: '1'
    - name: MP_NO_ENV_COMPAT
      value: '1'
    - name: MP_SET_midpoint_https_keystorePath
      value: /opt/midpoint/var/keystore.p12
    - name: MP_SET_midpoint_https_keystorePassword
      value: changeit
  initContainers:
    - name: wait-for-db
      image: postgres:16-alpine
      command:
        - sh
        - -c
        - |
          until pg_isready -h midpoint-postgres -p 5432 -U midpoint; do
            echo 'waiting for Postgres...'
            sleep 2
          done

    - name: init-native-repo
      image: evolveum/midpoint:4.8.4-alpine
      env:
        - name: MP_INIT_CFG
          value: /opt/midpoint/var/config.xml
        - name: MP_SET_midpoint_repository_jdbcPassword
          valueFrom:
            secretKeyRef:
              name: midpoint-db-secret
              key: POSTGRES_PASSWORD
        - name: MP_NO_ENV_COMPAT
          value: '1'
      command:
        - sh
        - -c
        - |
          set -e
          cd /opt/midpoint
          echo "Initializing native repository for PostgreSQL..."
          bin/midpoint.sh init-native
          echo "Repository initialization done."
      volumeMounts:
        - name: midpoint-home
          mountPath: /opt/midpoint/var
        - name: midpoint-config
          mountPath: /opt/midpoint/var/config.xml
          subPath: config.xml

  persistence:
    enabled: true
    name: midpoint-home
    size: 1Gi
    storageClass: ""
    hostPath: /mnt/data/midpoint
    accessModes:
      - ReadWriteOnce

  # HTTPS / Keystore configuration
  https:
    enabled: true
    keystore:
      secretName: midpoint-keystore
      path: /opt/midpoint/var/keystore.p12
      password: changeit   # Use a secret for production

# Volumes for ConfigMap
volumes:
  - name: midpoint-config
    configMap:
      name: midpoint-config

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: midpoint.local
      paths:
        - path: /midpoint
          pathType: Prefix
          servicePort: 8080
  tls: []

# Resources, tolerations, and affinity
resources: {}
tolerations: []
affinity: {}