apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-midpoint-postgres-0
  namespace: midpoint
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: midpoint-home-midpoint-0
  namespace: midpoint
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi