apiVersion: v1
kind: ConfigMap
metadata:
  name: midpoint-config
data:
  config.xml: |
    <configuration>
      <midpoint>
        <repository>
          <repositoryServiceFactoryClass>com.evolveum.midpoint.repo.sql.SqlRepositoryFactory</repositoryServiceFactoryClass>
          <jdbcUrl>jdbc:postgresql://midpoint-postgres:5432/midpoint</jdbcUrl>
          <jdbcUsername>midpoint</jdbcUsername>
          <jdbcPassword>${env:POSTGRES_PASSWORD}</jdbcPassword>
          <driverClassName>org.postgresql.Driver</driverClassName>
          <hibernateHbm2ddl>none</hibernateHbm2ddl>
          <missingSchemaAction>create</missingSchemaAction>
          <upgradeableSchemaAction>stop</upgradeableSchemaAction>
        </repository>
      </midpoint>
    </configuration>