apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.app.name }}
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      initContainers:
{{- range .Values.app.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          command: {{ toYaml .command | nindent 12 }}
{{- if .env }}
          env:
{{- range .env }}
            - name: {{ .name }}
{{- if .value }}
              value: {{ .value | quote }}
{{- else if .valueFrom }}
              valueFrom:
{{ toYaml .valueFrom | nindent 16 }}
{{- end }}
{{- end }}
{{- end }}
{{- if .volumeMounts }}
          volumeMounts:
{{ toYaml .volumeMounts | nindent 12 }}
{{- end }}
{{- end }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.service.port }}
          readinessProbe:
            {{- if .Values.app.readinessProbe.enabled }}
            httpGet:
              path: {{ .Values.app.readinessProbe.path }}
              port: {{ .Values.app.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            {{- end }}
          livenessProbe:
            {{- if .Values.app.livenessProbe.enabled }}
            httpGet:
              path: {{ .Values.app.livenessProbe.path }}
              port: {{ .Values.app.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
            {{- end }}
          env:
{{- range .Values.app.env }}
            - name: {{ .name }}
{{- if .value }}
              value: {{ .value | quote }}
{{- else if .valueFrom }}
              valueFrom:
{{ toYaml .valueFrom | nindent 16 }}
{{- end }}
{{- end }}
          volumeMounts:
            - name: {{ .Values.app.persistence.name }}
              mountPath: /opt/midpoint/var
      volumes:
        - name: {{ .Values.app.persistence.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.name }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.app.persistence.name }}
      spec:
        accessModes: {{ toYaml .Values.app.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.app.persistence.size }}