{{- range .Values.persistentVolumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  capacity:
    storage: {{ .capacity }}
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy | default "Retain" }}
  hostPath:
    path: {{ .hostPath.path }}
---
{{- end }}